# Cấu hình Máu và Tỉ lệ
chicken-health: 60.0
skill-chance: 0.75
base-damage: 5.0

# Cấu hình Warp (Nơi diễn ra trận đấu)
# Sử dụng lệnh /cw setwarp để tự động lưu tọa độ vào đây
warp:
  world: "world"
  x: 0.0
  y: 70.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0