name: ChickenWar
version: 5
main: com.example.chickenwar.ChickenWarPlugin
api-version: '1.21'
description: Dai chien ga dinh cao.
author: YourName
depend: [Vault]
commands:
  chickenwar:
    description: Lenh chinh cua plugin
    aliases: [cw]
    usage: /cw help
permissions:
  chickenwar.admin:
    description: Quyen Admin cho build/start/end/restart/setwarp/reload
    default: op